### ISSUE TITLE
Make the sidebar search respecting the sidebar ratios

### ISSUE THREAD

**Issue by vibe123456** [Soushi-Atsumi/Search-in-Sidebar#1]
The Sidebar search should responsivly react to the sidebar width -> i guess for most people it should use a mobile format?

This would be a huge improvement on the addon!

i appreciate your work!
David

**Comment by Soushi-Atsumi** [comment]
Hi, David100mark.

The format is determined by a site, not an add-on. Basically the format of a site depends on the user-agent and a size of window. However, it is not a feature for this add-on.

I am sorry to be so late for response. I thought I could receive a notification without adding a watch.

**Comment by Soushi-Atsumi** [comment]
[v4.0.0](https://github.com/Soushi-Atsumi/Search-in-Sidebar/releases/tag/v4.0.0) resolves this issue.
