### ISSUE TITLE
[Feature Request] Option to set a keyboard shortcut to close the sidebar 

### ISSUE THREAD

**Issue by pumaspoilagetrustable** [Soushi-Atsumi/Search-in-Sidebar#8]
Another feature that could be added to the extension would be the ability to set a keyboard shortcut to close the sidebar. The extension already has a different option to set a keyboard shortcut to open selected text as a search result in the sidebar. The shortcut to close the sidebar could be set to the "esc" key or any other combinations of keys that could be used as a keyboard shortcut such as "ctrl+alt+(insert letter)". 

Screenshot of option to set keyboard shortcut for opening the selected text as a search result in the sidebar:
![image](https://github.com/user-attachments/assets/cabccd26-7229-40e2-9bef-0dc079ab2ef6)

**Comment by Soushi-Atsumi** [comment]
I have added the feature of toggling. Closed by [v4.1.0](https://github.com/Soushi-Atsumi/Open-in-Sidebar/releases/tag/v4.1.0).
